[package]
name = "hyperpixel_init"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
bcm_host_sys = { path = "../bcm_host_sys" }
libc = "0.2.77"
log = "0.4.11"
pretty_env_logger = "0.4.0"
volatile = "0.4.1"
