[package]
name = "hyperpixel_init"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.32"
byteorder = "1.3.4"
libc = "0.2.77"
tracing = "0.1.19"
tracing-subscriber = "0.2.12"
