[package]
name = "hyperpixel_init"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
byteorder = "1.4.2"
libc = "0.2.95"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"

[profile.release]
lto = "fat"
